### ISSUE TITLE
Saga - Website go live checklist

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/design-system#20]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/design-system/issues/21
- [ ] https://github.com/grafana/design-system/issues/27
- [ ] https://github.com/grafana/design-system/issues/28
- [ ] https://github.com/grafana/design-system/issues/48
- [x] Cookie tracking consent banner
```
